env:
  - UGROOT="/home/travis/build/NeuroBox3D/ProMeshScripts/travis_root/ug4/"

addons:
    apt:
      packages:
       - make
       - cmake-data
       - cmake
      
git:
  depth: false    
  
language: cpp

dist: xenial

compiler:
    - gcc
    - clang

os:
  - linux
  - osx

jobs:
  include:
   - dist: bionic
   - dist: focal
   - dist: trusty
   - dist: precise
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXXFLAGS="-stdlib=libc++"; fi

before_script:
  - mkdir -p travis_root && cd travis_root
  - rm -rf ughub
  - git clone https://www.github.com/UG4/ughub
  - mkdir ug4 
  - cd ug4
  - ../ughub/ughub init .
  - ../ughub/ughub install ugcore ProMesh
  - mkdir -p BUILD
  - cd BUILD
  - cmake ../ -DTARGET=ugshell -DLAPACK=OFF -DBLAS=OFF -DProMesh=ON -DDIM="2;3" -DCPU=1
  
script:
    - travis_wait 45 make -j2
    - curl -O "https://raw.githubusercontent.com/NeuroBox3D/ProMeshScripts/master/polygonal_mesh_from_txt.lua"
    - ../bin/ugshell -ex polygonal_mesh_from_txt.lua -inputFolder ../../data -outputFileName test.ugx
    - file test.ugx
